---
title: "index"
author: "Maas Hermes"
date: "2023-03-01"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
---


```{r setup, include=FALSE}

library(flexdashboard)
library(plotly)
library(tidyverse)
library(spotifyr)
library(dplyr)
library(compmus)

# load playlists
flyMe_play <- get_playlist_audio_features("", "1tF2AxJkKufGgu6OTyWTgQ")
bobOmb_play <- get_playlist_audio_features("", "0zf0XjYpSmXZPe7VlVrJI6")
knitr::opts_chunk$set(echo = FALSE)


#Sys.setenv(SPOTIFY_CLIENT_ID = 'a34037c68c8c4321ab292374b43edd48')
#Sys.setenv(SPOTIFY_CLIENT_SECRET = 'c27edddbb73b47e191cdb8613b60c69b')
#access_token <- get_spotify_access_token()
```
# page 0 {.storyboard}

### Playlists
---
title: "Fly me to the moon"
output: html_document
---
  
```{r, out.extra=c('allow="encrypted-media"', 'allowtransparency="true"', 'frameBorder="0"')}
knitr::include_url("https://open.spotify.com/embed/playlist/1tF2AxJkKufGgu6OTyWTgQ?utm_source=generator", height = "380")
```

---
title: "Bob omb battlefield"
output: html_document
---
  
```{r, out.extra=c('allow="encrypted-media"', 'allowtransparency="true"', 'frameBorder="0"')}
knitr::include_url("https://open.spotify.com/embed/playlist/0zf0XjYpSmXZPe7VlVrJI6?utm_source=generator", height = "380")
```


# Page 1 {.storyboard}

### Plot 1: Fly me to the moon

```{r}
wood <- 
    get_tidy_audio_analysis('081AHcLTz6opbo1V9XN8eL') %>% 
    select(segments) %>% unnest(segments) %>% 
    select(start, duration, pitches)
    
wood %>% 
    mutate(pitches = map(pitches, compmus_normalise, 'euclidean')) %>% 
    compmus_gather_chroma %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = pitch_class, 
            fill = value)) + 
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    theme_minimal()
```

### Plot 2: Bob-omb Battlefield
```{r}
wood <- 
    get_tidy_audio_analysis('581IpQMQrx09Kn4YjiSlsr') %>% 
    select(segments) %>% unnest(segments) %>% 
    select(start, duration, pitches)
    
wood %>% 
    mutate(pitches = map(pitches, compmus_normalise, 'euclidean')) %>% 
    compmus_gather_chroma %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = pitch_class, 
            fill = value)) + 
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    theme_minimal()
```

# Page 2: Tempo{.storyboard}

### Histogram of Tempi of the two songs

```{r}
both <-
  bind_rows(
    flyMe_play |> mutate(category = "Fly me to the moon"),
    bobOmb_play |> mutate(category = "Bob-omb battlefield")
  )

both |>
  ggplot(aes(x = tempo)) +
  geom_histogram(binwidth = 10) +
  facet_wrap(~category)
```

<!-- ### Plot of Tempi  -->
<!-- ```{r} -->
<!-- both |>                    # Start with awards. -->
<!--   mutate( -->
<!--     mode = ifelse(mode == 0, "Minor", "Major") -->
<!--   ) |> -->
<!--   ggplot(                     # Set up the plot. -->
<!--     aes( -->
<!--       x = valence, -->
<!--       y = energy, -->
<!--       size = loudness, -->
<!--       colour = mode -->
<!--     ) -->
<!--   ) + -->
<!--   geom_point() +              # Scatter plot. -->
<!--   geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution. -->
<!--   geom_text(                  # Add text labels from above. -->
<!--     aes( -->
<!--       x = duration_ms, -->
<!--       y = tempo, -->
<!--       label = label -->
<!--     ), -->
<!--     data =  -->
<!--       tibble( -->
<!--         label = c("Altijd wel iemand", "ENERGY"), -->
<!--         category = c("Edisons", "Grammys"), -->
<!--         valence = c(0.090, 0.123), -->
<!--         energy = c(0.101, 0.967) -->
<!--       ), -->
<!--     colour = "black",         # Override colour (not mode here). -->
<!--     size = 3,                 # Override size (not loudness here). -->
<!--     hjust = "left",           # Align left side of label with the point. -->
<!--     vjust = "bottom",         # Align bottom of label with the point. -->
<!--     nudge_x = -0.05,          # Nudge the label slightly left. -->
<!--     nudge_y = 0.02            # Nudge the label slightly up. -->
<!--   ) + -->
<!--   facet_wrap(~ category) +    # Separate charts per playlist. -->
<!--   scale_x_continuous(         # Fine-tune the x axis. -->
<!--     limits = c(0, 1), -->
<!--     breaks = c(0, 0.50, 1),   # Use grid-lines for quadrants only. -->
<!--     minor_breaks = NULL       # Remove 'minor' grid-lines. -->
<!--   ) + -->
<!--   scale_y_continuous(         # Fine-tune the y axis in the same way. -->
<!--     limits = c(0, 1), -->
<!--     breaks = c(0, 0.50, 1), -->
<!--     minor_breaks = NULL -->
<!--   ) + -->
<!--   scale_colour_brewer(        # Use the Color Brewer to choose a palette. -->
<!--     type = "qual",            # Qualitative set. -->
<!--     palette = "Paired"        # Name of the palette is 'Paired'. -->
<!--   ) + -->
<!--   scale_size_continuous(      # Fine-tune the sizes of each point. -->
<!--     trans = "exp",            # Use an exp transformation to emphasise loud. -->
<!--     guide = "none"            # Remove the legend for size. -->
<!--   ) + -->
<!--   theme_light() +             # Use a simpler theme. -->
<!--   labs(                       # Make the titles nice. -->
<!--     x = "Valence", -->
<!--     y = "Energy", -->
<!--     colour = "Mode" -->
<!--   ) -->
<!-- ``` -->